title = "Javacos A40 config"

[measurement]
trigger_threshold = 40
posttrigger_delay = 0
number_of_samples = 10_000_000
sample_interval = 25
channel_range = 200

[extraction]
max_gap = 10_000
min_duration = 50_000
threshold = 0
index_to_extract = -1
