title = "Infineon Secora config"

[capture]
autotrigger = 5000
posttrigger_delay = 2600
number_of_samples = 9_000_000
sample_interval = 50
channel_range = 500

# for raw trace
[extraction]
max_gap = 6000
min_duration = 2500
threshold = 0.65
index_to_extract = 0

## for resampled trace
#[extraction]
#max_gap = 500
#min_duration = 2500
#threshold = 0.35
#index_to_extract = 0

#[analysis]
#alignment_threshold = 0.5
#ignore_first_n = 3_100_000
#diff_threshold = 0.3

# --key 404142434445464748494A4B4C4D4E4F404142434445464748494A4B4C4D4E4F'
