title = "Javacos A40 config"

[measurement]
trigger_threshold = 1000
posttrigger_delay = 3200 #3100
number_of_samples = 15_000_000
sample_interval = 50 #50
channel_range = 500

[extraction]
max_gap = 4000
min_duration = 1300
threshold = 0.4
index_to_extract = -1
