title = "Javacos A40 config"

[capture]
trigger_threshold = 80
autotrigger = 5000
posttrigger_delay = 2700
number_of_samples = 4_000_000
sample_interval = 50
channel_range = 500

## for resampled trace
#[extraction]
#max_gap = 4000
#min_duration = 1300
#threshold = 0.4
#index_to_extract = 6

#for raw trace
[extraction]
max_gap = 7000
min_duration = 4000
threshold = 0.6
index_to_extract = 6 #28

# ignore_first_n = 1_200_000
# diff_threshold = 0.85
# alignment_threshold = 0.8