title = "NXP JCOP 4 config"

[capture]
autotrigger = 5000
posttrigger_delay = 3280
number_of_samples = 9_000_000
sample_interval = 50
channel_range = 500

[extraction]
max_gap = 1000
min_duration = 700
threshold = 0.6
index_to_extract = 24 #108

#[extraction]
#max_gap = 100
#min_duration = 800
#threshold = 0.5
#index_to_extract = 24
