title = "G&D Smartcafe 6.0 config"

[capture]
autotrigger = 5000
posttrigger_delay = 3000
number_of_samples = 15_000_000
sample_interval = 50
channel_range = 100

[extraction]
max_gap = 500
min_duration = 18_000
threshold = 0.9
index_to_extract = 30

#[analysis]
#alignment_threshold = 0.6
#ignore_first_n = 6_700_000
#diff_threshold = 0.1
